server:
  port: 18083
  servlet:
    session:
      timeout: 60
spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/db/bookstore.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

mybatis:
#  mapper-locations: classpath*:io/parcelx/**/mapper/xml/**.xml
#  type-aliases-package: io.parcelx
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
